<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '',
    'Авторизация' => '',
    'Админпанель' => '',
    'Активен' => 'Active',
    'Активна' => 'Active',
    'Войти' => '',
    'Выбор фото для "{name}" завершен' => 'Photo selecting is done for "{name}"',
    'Выбранные фото' => '',
    'Выбрано максимальное количество фото' => 'You\'ve selected maximum count of photos',
    'Выйти' => '',
    'Дата Завершения' => 'Date Submitted',
    'Дата Создания' => 'Date Created',
    'Добавить' => '',
    'Завершено Пользователем' => 'Submitted',
    'Запомнить' => 'Remember me',
    'Изменить Проект: {name}' => '',
    'Изменить Ссылку: {name}' => '',
    'Комментарий' => '',
    'Комментирование не разрешено' => 'Commenting is not allowed',
    'Копировать ссылку в буфер обмена' => '',
    'Логин' => 'Login',
    'Макс. Фото' => 'Max Selected Photos',
    'Максимальное количество фото, которые можно выбрать. 0 - без ограничений' => '',
    'Название' => 'Name',
    'Нельзя изменить это фото' => '',
    'Неправильный логин или пароль' => '',
    'Описание' => 'Description',
    'Основное' => '',
    'Отключить после завершения' => 'Disable after submit',
    'Отключить скачивание фото' => 'Disable downloading',
    'Параметры' => '',
    'Пароль' => 'Password',
    'Перейдите по ссылке, которую дал фотограф' => 'You need to click on link',
    'Показывать инструкцию' => 'Show guide',
    'Проект' => 'Project',
    'Проект не найден' => '',
    'Проекты' => '',
    'Разрешить комментирование' => 'Allow commenting',
    'Редактирование' => '',
    'Создать Проект' => '',
    'Создать Ссылку' => '',
    'Сообщение Приветствия' => 'Greeting Message',
    'Сообщение отсутствует' => 'Message is empty',
    'Сохранить' => '',
    'Ссылка' => 'Link',
    'Ссылка не найдена' => 'Link doesn\'t exist',
    'Ссылки' => '',
    'Ставить watermark' => 'Place watermark',
    'Фото не найдено' => 'Photo doesn\'t exist',
];
